<?php 
/*
 * Magepow
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @license: http://www.magepow.com/license-agreement
 * @Author: DavidDuong
 * @@Create Date: Wednesday, December 4th 2019, 8:43:54 pm
 * @@Modified By: DavidDuong
 * @@Modify Date: Friday, December 6th 2019, 3:41:40 pm
 */ 

$_product = $block->getProduct();

$prev_product = $block->getPrevProduct($_product);
$next_product = $block->getNextProduct($_product);
$current_category = $block->getCurrentCategory($_product);
$name_category = $current_category->getName();
$url_category = $current_category->getUrl();
$enable = $block->getConfigure();
?>
<?php if($enable && ($prev_product || $next_product)): ?>
    <div class="product-next-prev">
    	
            <?php 
                if($name_category){
                    ?>
                    <div class="back_category">
                        <a href="<?php echo $url_category; ?>"><?php echo __('Back to:') ?> <?php echo $name_category; ?></a>
                    </div>
                    <?php
                }
            ?>
    	
        <?php if($next_product): ?>
            <a class="product-next" title="<?php echo __('Next') ?>" href="<?php echo $next_product->getProductUrl(); ?>"><span>></span></a>
        <?php endif; ?>
        <?php if($prev_product): ?>
            <a class="product-prev" title="<?php echo __('Previous') ?>" href="<?php echo $prev_product->getProductUrl(); ?>"><span><</span></a>
        <?php endif; ?>
    </div> 
<?php endif; ?>
