/*
 * Magepow
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @license: http://www.magepow.com/license-agreement
 * @Author: DavidDuong
 * @@Create Date: Wednesday, December 4th 2019, 8:43:54 pm
 * @@Modified By: DavidDuong
 * @@Modify Date: Thursday, December 5th 2019, 9:58:46 am
 */

<?php 
    $_product = $block->getProduct();

    $prev_product = $block->getPrevProduct($_product);
    $next_product = $block->getNextProduct($_product);
?>
<?php if($prev_product || $next_product): ?>
    <div class="product-next-prev">
        <?php if($prev_product): ?>
            <a class="product-next" title="Next" href="<?php echo $prev_product->getProductUrl(); ?>"><span><</span></a>
        <?php endif; ?>

        <?php if($next_product): ?>
            <a class="product-prev" title="Previous" href="<?php echo $next_product->getProductUrl(); ?>"><span>></span></a>
        <?php endif; ?>
    </div> 
<?php endif; ?>